<a href="https://colab.research.google.com/github/alyacipta/AI-Data-Projects/blob/main/RDKIT-Python/Immune_System_LOA_Ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Install RDKit.
# %%capture
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (37.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.0/37.0 MB 48.7 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.1

In [5]:
# Importing Libraries
import pandas as pd
import numpy as np
import warnings

from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import Descriptors
from rdkit.Chem import AllChem, PandasTools, MACCSkeys, AtomPairs, rdFingerprintGenerator
from rdkit import DataStructs
from rdkit.Chem.rdmolops import PatternFingerprint
from rdkit.Avalon import pyAvalonTools
from rdkit.Chem.AtomPairs.Pairs import GetAtomPairFingerprintAsBitVect
pd.set_option('display.max_rows', None)

warnings.filterwarnings("ignore")

In [7]:
df = pd.read_excel('/content/sider.xlsx')

In [9]:
print(df.columns)
# Adding .copy() creates a new independent dataframe
df = df[['smiles', 'Immune system disorders']].copy()

Index(['smiles', 'Hepatobiliary disorders',
       'Metabolism and nutrition disorders', 'Product issues', 'Eye disorders',
       'Investigations', 'Musculoskeletal and connective tissue disorders',
       'Gastrointestinal disorders', 'Social circumstances',
       'Immune system disorders', 'Reproductive system and breast disorders',
       'Neoplasms benign, malignant and unspecified (incl cysts and polyps)',
       'General disorders and administration site conditions',
       'Endocrine disorders', 'Surgical and medical procedures',
       'Vascular disorders', 'Blood and lymphatic system disorders',
       'Skin and subcutaneous tissue disorders',
       'Congenital, familial and genetic disorders',
       'Infections and infestations',
       'Respiratory, thoracic and mediastinal disorders',
       'Psychiatric disorders', 'Renal and urinary disorders',
       'Pregnancy, puerperium and perinatal conditions',
       'Ear and labyrinth disorders', 'Cardiac disorders',
       'Nervous system disorders',
       'Injury, poisoning and procedural complications'],
      dtype='object')

In [10]:
df = df.dropna(subset=['smiles'])

In [11]:
df

,smiles,Immune system disorders
0,C(CNCCNCCNCCN)N,0
1,CC(C)(C)C1=CC(=C(C=C1NC(=O)C2=CNC3=CC=CC=C3C2=...,0
2,CC[C@]12CC(=C)[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O...,1
3,CCC12CC(=C)C3C(C1CC[C@]2(C#C)O)CCC4=CC(=O)CCC34,1
4,C1C(C2=CC=CC=C2N(C3=CC=CC=C31)C(=O)N)O,1
5,CC[C@H](C)[C@H]1C(=O)N[C@H]2CSSC[C@@H](C(=O)N[...,1
6,CC1CC2C3CCC4=CC(=O)C=CC4([C@]3(C(CC2([C@]1(C(=...,1
7,CCCCCCOC(=O)N=C(C1=CC=C(C=C1)NCC2=NC3=C(N2C)C=...,1
8,CSCCC(C(=O)NCC(=O)NC(CC1=CNC2=CC=CC=C21)C(=O)N...,1
9,C1CC(N(C1)C(=O)C2CSSCC(C(=O)NC(C(=O)NC(C(=O)NC...,1
10,CC(C)CN(C[C@H]([C@H](CC1=CC=CC=C1)NC(=O)O[C@H]...,1
11,C1CC[C@H]([C@@H](C1)CN2CCN(CC2)C3=NSC4=CC=CC=C...,0
12,CCCSC1=NC2=C(C(=N1)N[C@@H]3C[C@H]3C4=CC(=C(C=C...,1
13,C1CN(CC2=C1SC=C2)CC3=CC=CC=C3Cl,1
14,Cl[Tl],1
15,CC1=NN=C(N1C2CC3CCC(C2)N3CC[C@@H](C4=CC=CC=C4)...,1
16,C[N+](C)(C)CC(CC(=O)O)O,1
17,CN1C2=C(C=C(C=C2)N(CCCl)CCCl)N=C1CCCC(=O)O,1
18,CCN(CC)C(=O)/C(=C/C1=CC(=C(C(=C1)O)O)[N+](=O)[...,1
19,C(CC(=O)O)CN,1
20,C[C@H]1C[C@H]2[C@@H]3C[C@@H](C4=CC(=O)C=C[C@@]...,0
21,CC(C)CN1C=NC2=C1C3=CC=CC=C3N=C2N,1
22,CC[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC...,1
23,CC1=CC(=C(N1)C=C2C3=CC=CC=C3NC2=O)C,1
24,C(CC(=O)O)C(=O)CN,0
25,C1C(N(C2=C(N1)NC(=NC2=O)N)C=O)CNC3=CC=C(C=C3)C...,1
26,CCC12CC(=C)C3C(C1CC[C@]2(C#C)O)CCC4=CC(=O)CCC3...,1
27,CN1C(CNC2=C1C(=O)N=C(N2)N)CNC3=CC=C(C=C3)C(=O)...,1
28,CCCCC(=O)O[C@@]1([C@H](C[C@@H]2[C@@]1(C[C@@H](...,1
29,CC[C@H](C)[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[...,1
30,CCCCCC(C=CC1C(CC(=O)C1CC=CCCCC(=O)O)O)O,1
31,CCCCCC(C=CC1C(CC2C1CC(=CCCCC(=O)O)O2)O)O,1
32,CCCCCC(C=CC1C(CC(C1CC=CCCCC(=O)O)O)O)O,1
33,CC(=O)O.C(C(C(C(C(C=O)O)O)O)O)O,1
34,CC(=O)[O-],0
35,CC(=O)OCC[N+](C)(C)C,0
36,C1=NC2=C(C(=N1)N)N=CN2C3C(C(C(O3)CO)O)O,1
37,CCCN(CCC1=CC=CS1)C2CCC3=C(C2)C=CC=C3O,1
38,C1=CO[C@@H]([C@H]([C@@H]1O)O)C(=O)O.Cl,1
39,C(C1C(C(C(C(O1)O)O)O)O)O,0
40,CCCCCC(C=CC1C(CC(=O)C1CCCCCCC(=O)O)O)O,0
41,N,0
42,CC1=CC2=C(C=C1C(=C)C3=CC=C(C=C3)C(=O)O)C(CCC2(...,1
43,CC(=O)NCCC1=CC=CC2=C1C=C(C=C2)OC,0
44,C(CC(C(=O)O)N)CN=C(N)N,1
45,C1=CC=C(C=C1)CO,0
46,C[N+](C)(C)CC(=O)[O-],0
47,CC[C@H](C)[C@@H](C(=O)N[C@@H](CC1=CC=C(C=C1)O)...,1
48,CCCC1=NC(=C2N1NC(=NC2=O)C3=C(C=CC(=C3)S(=O)(=O...,1
49,CN1CC(=O)N2[C@@H](C1=O)CC3=C([C@H]2C4=CC5=C(C=...,1
50,I,1
51,[Ca+2],1
52,C[C@]12CCC(=O)C=C1[C@@H]3C[C@@H]3[C@@H]4[C@@H]...,0
53,C,0
54,C1=CC(=CC=C1C(C(CO)NC(=O)C(Cl)Cl)O)[N+](=O)[O-],1
55,CC(CCC(=O)O)C1CCC2C1(C(CC3C2C(CC4C3(CCC(C4)O)C...,0
56,CC1=NC=CN1.C1C(O1)CCl,0
57,C[N+](C)(C)CCO,0
58,C(C(=O)O)C(CC(=O)O)(C(=O)O)O,0
59,[Cl-],0
60,COC1=CC=C(C=C1)N2C3=C(CCN(C3=O)C4=CC=C(C=C4)N5...,1
61,CCOC1=CC=CC=C1O[C@H]([C@@H]2CNCCO2)C3=CC=CC=C3,1
62,C1=CC2=C(C(=C1)Cl)SC=C2COC(CN3C=CN=C3)C4=C(C=C...,0
63,CC1=C(C(C(=C(N1)C)C(=O)OC(C)(C)CN(C)CCC(C2=CC=...,1
64,C1=CC=C(C(=C1)C(=O)O)O,0
65,CC1=CC=CN2C1=NC=C(C2=O)C3=NNN=N3,1
66,CC1=CC(=C(C(=C1C=CC(=CC=CC(=CC(=O)O)C)C)C)C)OC,1
67,C1C(C(=O)NO1)N,1
68,CCN(CC)CCOC(=O)C1=C(C=C(C=C1)N)Cl,0
69,CCOC1=CC=CC=C1OCCN[C@@H](C)CC2=CC(=C(C=C2)OC)S...,1
70,CC(C(=O)C1=CC(=CC=C1)Cl)NC(C)(C)C,1
71,CC12CCC3C(C1CCC2O)CCC4=C3C=CC(=C4)O,1
72,C(C(C(C(C(CO)O)O)O)O)O,1
73,CC[C@@H]([C@H](C)O)N1C(=O)N(C=N1)C2=CC=C(C=C2)...,1
74,CC(C)CN(C[C@H]([C@H](CC1=CC=CC=C1)NC(=O)O[C@H]...,1
75,C1=CC=C2C(=C1)C(=O)OC23C4=C(C=C(C=C4)O)OC5=C3C...,1
76,CCC1=NC=CC(=C1)C(=S)N,1
77,C1C(C(OC1N2C=NC(=NC2=O)N)CO)O,1
78,C1=CC=C(C=C1)C2=NC3=C(N=C2N)N=C(N=C3N)N,1
79,CC1=C(C(=O)N2CCCC(C2=N1)O)CCN3CCC(CC3)C4=NOC5=...,1
80,C(CCC(=O)O)CCN,1
81,CC(=O)NC(CS)C(=O)O,1
82,CN1CCC23C4C1CC5=C2C(=C(C=C5)OC)OC3C(C=C4)O,1
83,C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O,1
84,C(CS(=O)(=O)O)S,1
85,CNC1=CC=C(C=C1)/C=C/C2=CN=C(C=C2)OCCOCCOCC[18F],0
86,CC(C(=O)O)O,0
87,CN1C2=C(C(=O)N(C1=O)C)NC=N2.C[N+](C)(C)CCO,0
88,C#CCC(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C...,0
89,C1CC(=O)C(C(=O)C1)C(=O)C2=C(C=C(C=C2)C(F)(F)F)...,0
90,C1=CC=C(C=C1)C(=C(C2=CC=CC=C2)C3=CC=C(C=C3)OCC...,0
91,[H+].[H+].CNC[C@@H]([C@H]([C@@H]([C@@H](CO)O)O...,1
92,CN1C[C@@H]2C(C1)C3=CC=CC=C3OC4=C2C=C(C=C4)Cl,1
93,CS(=O)C,0
94,C1=CC(=C(C=C1CCN)O)O,0
95,CC12CCC3C(C1CCC2=O)CCC4=C3C=CC(=C4)O,1
96,CC12CCC3C(C1CCC2=O)CCC4=C3C=CC(=C4)OS(=O)(=O)O,1
97,C(CO)N,1
98,C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3...,1
99,CC(C)OC(=O)CCCC=CC[C@H]1[C@H](C[C@H]([C@@H]1C=...,1
100,CC(=O)OC1=CC=CC=C1C(=O)NC2=NC=C(S2)[N+](=O)[O-],1
101,CN(C)CCC1=CNC2=C1C=C(C=C2)CS(=O)(=O)N3CCCC3,1
102,C1(C(C(C(C(C1Cl)Cl)Cl)Cl)Cl)Cl,0
103,C1CC2C(=O)NC(CSSCCC(=O)NC(C(=O)NCC(=O)NC(C(=O)...,1
104,CO[C@@H]1[C@@H]([C@H]([C@@H]([C@H](O1)COS(=O)(...,1
105,CCC(=O)N(C1=CC=CC=C1)C2(CCN(CC2)CCC3=CC=CS3)COC,1
106,CC1CCC2CC(C(=CC=CC=CC(CC(C(=O)C(C(C(=CC(C(=O)C...,1
107,CC(C)(C)[C@@H](C(=O)N[C@@H](CC1=CC=CC=C1)[C@H]...,1
108,C(CC(=O)N)C(C(=O)O)N,1
109,CC1=NC=C(C=C1)C2=NC=C(C=C2C3=CC=C(C=C3)S(=O)(=...,1
110,C[C@@H]1C[C@H]2C3CCC4=CC(=O)C=C[C@@]4([C@]3([C...,1
111,C[C@]12CCC(=O)C=C1C[C@H](C3[C@]24C(O4)C[C@]5([...,0
112,CC1=C2C(=C(N(C1=O)C)NC3=C(C=C(C=C3)I)F)C(=O)N(...,0
113,CCC(C)CC(C)CCCCCCCCC(=O)N[C@H]1C[C@@H]([C@H](N...,1
114,C(C(=O)O)N,1
115,COC1=C(C=C2C(=C1)N=CN=C2NC3=CC(=C(C=C3)F)Cl)OC...,1
116,C(C(CO)O)O,1
117,CC(=O)O[C@]1(CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC...,1
118,C1C[C@H]2CN(C(=O)C3=C2C(=CC=C3)C1)[C@@H]4CN5CC...,1
119,C(=O)(O)O,0
120,C[C@H](C1=CC=CC2=CC=CC=C21)NCCCC3=CC(=CC=C3)C(...,1
121,CC(=O)NC1C(C(C(OC1O)COS(=O)(=O)O)OC2C(C(C(C(O2...,1
122,C1=C(NC=N1)CCN,1
123,CCCCC(=O)OCC(=O)[C@]1(C[C@@H](C2=C(C3=C(C(=C2C...,0
124,C1=CC(=CC=C1O)O,1
125,CCOC1=C(C2=CC=CC=C2C=C1)C(=O)N[C@H]3[C@@H]4N(C...,1
126,[K+],0
127,C[C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@@H]2[C...,1
128,C1C(C(C(C(C1N)OC2C(C(C(C(O2)CN)O)O)O)O)OC3C(C(...,0
129,CC1=CC(=CC=C1)NC2=C(C=NC=C2)S(=O)(=O)NC(=O)NC(C)C,0
130,C1CC(N(C1)C(=O)CNC23CC4CC(C2)CC(C4)(C3)O)C#N,0
131,CNCC(C1=CC(=C(C=C1)O)O)O,0
132,CCC#CC(C)C1(C(=O)NC(=O)N(C1=O)C)CC=C,1
133,C(P(=O)(O)O)(P(=O)(O)O)(Cl)Cl,1
134,C1=C(C=C(C(=C1I)OC2=CC(=C(C(=C2)I)O)I)I)CC(C(=...,1
135,C1=CC(=C(C=C1OC2=C(C=C(C=C2I)CC(C(=O)O)N)I)I)O,0
136,[Mg+2],0
137,CC(=O)NCCC1=CNC2=C1C=C(C=C2)OC,1
138,CCNC(=NCCCC[C@H](C(=O)N[C@@H](CC(C)C)C(=O)N[C@...,1
139,[Na+],1
140,C1=CC(=C(C=C1C[C@@H](C(=O)O)N)O)O.C1=CC(=C(C(=...,0
141,C1=CC(=CN=C1)C(=O)[O-],1
142,CCO.C[C@@H]1C2C(C3[C@@H](C(=O)C(=C([C@]3(C(=O)...,1
143,CN1CCCC1C2=CN=CC=C2,1
144,N(=O)[O-],0
145,N#[N+][O-],0
146,CC(=O)[O-].[Na+],0
147,C1=CC(=C(C=C1C(CN)O)O)O,0
148,[OH-],0
149,FS(F)(F)(F)(F)F,1
150,OP(=O)(O)[O-],1
151,CN[C@@H]1CCC2=C(C1)C3=C(N2)C=CC(=C3)C(=O)N,1
152,C[C@H](C(=O)N1CCC[C@H]1C(=O)O)N[C@@H](CCC2=CC=...,1
153,CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CCCC(=O)OCC.CC/...,1
154,C1CN(CCN1CCCCC2=CNC3=C2C=C(C=C3)C#N)C4=CC5=C(C...,0
155,C=CC1=C(N2[C@@H]([C@@H](C2=O)NC(=O)C(=NO)C3=CS...,1
156,C[C@H](C=C[C@H](C)C(C)(C)O)[C@H]1CC[C@@H]2[C@@...,1
157,C1=CN=C(C=N1)C(=O)N,1
158,CC1=NC=C(C(=C1O)CO)CO,0
159,COC1=CC2=C(C=CN=C2C=C1)C(C3CC4CCN3CC4C=C)O,1
160,CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C,1
161,CCC(=O)OC1([C@@H](C[C@@H]2[C@@]1(C[C@@H](C3([C...,1
162,CC[C@H](C)[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[...,1
163,C[C@@H]1C[C@H]2[C@@H]3C[C@@H](C4=CC(=O)C=C[C@@...,1
164,CC1=CC(=NC(=N1)OC(C(=O)O)C(C2=CC=CC=C2)(C3=CC=...,1
165,C(C[Ge](=O)O[Ge](=O)CCC(=O)O)C(=O)O,1
166,C1C[N+]2(CCC1(CC2)C(C3=CC=CC=C3)(C4=CC=CC=C4)O...,0
167,CC(C(C1CNC2=C(N1)C(=O)N=C(N2)N)O)O,1
168,C(COC[C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)OCCO)O...,1
169,CC1=C(SC=[N+]1CC2=CN=C(N=C2N)C)CCO,1
170,CC1=CN(C(=O)NC1=O)C2CC(C(O2)CO)O,0
171,CCCC1=C2C(=CC3=C1OC(=CC3=O)C(=O)O)C(=O)C=C(N2C...,1
172,C(C(F)(F)F)(OC(F)F)F,0
173,C(C(C(=O)O)S)(C(=O)O)S,1
174,C[C@H](C(=O)N)NC(=O)[C@@H]1CCCN1C(=O)[C@H](CCC...,1
175,CN1CCC(CC1)COC2=C(C=C3C(=C2)N=CN=C3NC4=C(C=C(C...,0
176,CCCCCCCCCCNCCN[C@]1(C[C@@H](O[C@H]([C@H]1O)C)O...,1
177,CC(=O)[C@]1(CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2C=C(...,1
178,CC(CC1=CC=CC=C1)NC,1
179,C1CC2=C(C=CC(=C2)Cl)C(=C3CCNCC3)C4=C1C=CC=N4,1
180,CN1C2=C(C(=O)N(C1=O)C)NC=N2.CN1C2=C(C(=O)N(C1=...,1
181,C1CC(CCC1C2=CC=C(C=C2)Cl)C3=C(C4=CC=CC=C4C(=O)...,1
182,C[C@H]([C@@H](C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H]...,1
183,C[C@@H](CC1=CC2=C(C(=C1)C(=O)N)N(CC2)CCCO)NCCO...,1
184,CCC1/C=C(/C(C/C=C/C=C(\C(=O)OC(C/C=C(/C=C(/C1O...,1
185,CC(C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)[O-].[Na+],1
186,COC1=C(C=C(C=C1)CCO[C@@H]2CCCC[C@H]2N3CC[C@H](...,0
187,C1[C@H](SC(=C(C#N)N2C=CN=C2)S1)C3=C(C=C(C=C3)C...,0
188,CCCCC1=NC2(CCCC2)C(=O)N1CC3=CC=C(C=C3)C4=CC=CC...,1
189,CC[C@H](C)[C@@H](C(=O)N[C@@H]([C@@H](C)O)C(=O)...,0
190,C[C@]12C[C@@H]([C@]3([C@H]([C@@H]1C[C@H]([C@@]...,0
191,[C-]#N.[C-]#N.[C-]#N.[C-]#N.[C-]#N.[C-]#N.[Fe+2],0
192,CC1=C(C=CC2=C1N=C(C=C2OC3C[C@@H]4[C@@H](C3)C(=...,0
193,CCCCC(=O)O[C@@]1(CCC2C1(CC(C3C2CCC4=CC(=O)CCC3...,0
194,CN1C(=NN=N1)SCC2=C(N3C([C@@](C3=O)(NC(=O)C4SC(...,1
195,CC[PH+](CC)CC.CC[PH+](CC)CC.CC(=O)OCC1C(C(C(C(...,0
196,CCCCCCCCC1=CC=C(C=C1)CCC(CO)(CO)N.Cl,1
197,CC[C@H](C)[C@H]1C(=O)N[C@H](C(=O)N[C@H](C(=O)N...,1
198,CC(C)[C@@H](CO)N1C=C(C(=O)C2=CC(=C(C=C21)OC)CC...,1
199,C[C@H]1C=CC=C(C(=O)NC2=C3C(=NC4(N3)CCN(CC4)CC(...,1
200,C[C@@H](C(=O)N1CC2=CC=CC=C2C[C@H]1C(=O)O)N[C@@...,1
201,CC[C@H](C)[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[...,1
202,CC(=O)C1(CCC2C1(CC(C3=C4CCC(=O)C=C4CCC23)C5=CC...,0
203,CN(C)CC[C@@](C1=CC=CC2=CC=CC=C21)([C@@H](C3=CC...,0
204,C1CCC(CC1)[C@@H]2C[C@H](NC2)C(=O)O,1
205,C1C2=CC=CC=C2N(C3=CC=CC=C3C1=O)C(=O)N,1
206,C1C(C(OC1N2C=NC3=C2N=C(N=C3N)Cl)CO)O,1
207,[H-].[H-].[Ba+2],0
208,C[C@]12CCC(=O)C=C1CC[C@@H]3[C@@H]2C(=O)C[C@]4(...,1
209,CCOC(=O)N[C@@H]1CC[C@@H]2[C@@H](C1)C[C@@H]3[C@...,0
210,CC1=C(SC=N1)C=CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O...,1
211,COCCNC(=O)CN(CCN(CCN(CC(=O)NCCOC)CC(=O)[O-])CC...,1
212,CCNC(=O)C1CCCN1C(=O)C(CCCN=C(N)N)NC(=O)C(CC(C)...,1
213,CC(C)C(=O)OCC(=O)[C@@]12[C@@H](C[C@@H]3[C@@]1(...,1
214,C(CC(C(F)F)(C(=O)O)N)CN,0
215,[H-].[H-].[Sr+2],0
216,CC1C(C(CC(O1)OC2CC(CC3=C(C4=C(C(=C23)O)C(=O)C5...,1
217,C[C@@H](C(=O)O)N.CC(=O)O.C1=CC(=CC=C1C[C@@H](C...,1
218,CC(C)C[C@@H](C(=O)N[C@@H](CCCN=C(N)N)C(=O)N1CC...,0
219,CC1(C(=O)N(C(=S)N1C2=CC(=C(C=C2)C(=O)NC)F)C3=C...,0
220,C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=CC...,0
221,CS(=O)(=O)O.C1CNC[C@H]([C@@H]1C2=CC=CC=C2)COC3...,1
222,C1CC1C2=NC3=CC=CC=C3C(=C2C=C[C@H](C[C@H](CC(=O...,1
223,CC12CCC3C(C1CCC2O)CCC4=C3C=CC(=C4)OC(=O)N(CCCl...,0
224,CC1CC2C3C(CC4=CC(=O)C=CC4(C3C(CC2(C1(C(=O)CO)O...,0
225,C1=CC=C(C=C1)C2(C(=O)NC(=O)N2)C3=CC=CC=C3,1
226,[H+].[H+].C(CN(CC(=O)[O-])CC(=O)[O-])N(CCN(CC(...,1
227,CC1=NN=C(O1)C(=O)NC(C)(C)C2=NC(=C(C(=O)N2C)[O-...,1
228,CC(=O)NC1=[N+](N=C(S1)S(=O)(=O)N)C,1
229,C1=NC(=NC(=O)N1C2C(C(C(O2)CO)O)O)N,1
230,CC1CC2C3CCC(C3(CC(C2C4(C1=CC(=O)C=C4)C)O)C)(C(...,1
231,C[C@]12CC[C@@H](CC1=CC[C@@H]3[C@@H]2CC[C@]4([C...,0
232,CNC(=O)C1=NC=CC(=C1)OC2=CC(=C(C=C2)NC(=O)NC3=C...,0
233,CCC(=O)O[C@](CC1=CC=CC=C1)(C2=CC=CC=C2)[C@H](C...,1
234,CN(CCCN1CCC2=CC(=C(C=C2CC1=O)OC)OC)C[C@H]3CC4=...,0
235,CCCC1=CC(=O)NC(=S)N1,0
236,C(C=O)C(C=O)O,1
237,C1CC1NC2=NC(=NC3=C2N=CN3C4CC(C=C4)CO)N,1
238,CC1C=CC=CC=CC=CC=CC=CC=CC(CC2C(C(CC(O2)(CC(CC(...,1
239,CCCC(=O)NC1=CC(=C(C=C1)OCC(CNC(C)C)O)C(=O)C,0
240,CC(=O)NC1=CC=C(C=C1)O,1
241,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,1
242,CC(=O)NO,0
243,CCCCCCCCCCCCCCCCCCCCCCO,0
244,CCCCC(C)(CC=C[C@H]1[C@@H](CC(=O)[C@@H]1CCCCCCC...,1
245,C1C[C@H](N(C1)C(=O)[C@@H]2CSSC[C@@H](C(=O)N[C@...,0
246,C([C@@H]([C@@H]1C(=O)C(=C(O1)[O-])[O-])O)O.[Ca+2],0
247,CC1C(C(=O)NC(C(=O)N2CCCC2C(=O)N(CC(=O)N(C(C(=O...,1
248,CC1CC(=O)C2(C(O1)OC3C(C(C(C(C3O2)NC)O)NC)O)O,1
249,C1=NC2=C(N1COCCO)NC(=NC2=O)N,1
250,C=CCN.C1C(O1)CCl.C(=O)(O)O,0
251,[As],1
252,CO[C@@H]1[C@H]([C@@H]([C@@H](O[C@@H]1C(=O)[O-]...,1
253,CC[C@@]12C=CCN3[C@@H]1[C@]4(CC3)[C@H]([C@]([C@...,1
254,CCOC1=NC2=CC=CC(=C2N1CC3=CC=C(C=C3)C4=CC=CC=C4...,0
255,CCCSC1=CC2=C(C=C1)N=C(N2)NC(=O)OC,1
256,CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O,1
257,CCC(=O)OCC(=O)C1(C(CC2C1(CC(C3C2C(CC4=CC(=O)C=...,0
258,C(CC(O)(P(=O)(O)O)P(=O)(O)O)CN,1
259,CN(CCCNC(=O)C1CCCO1)C2=NC3=CC(=C(C=C3C(=N2)N)O...,0
260,C1=C2C(=NC=NC2=O)NN1,1
261,CC1=C(N=CN1)CN2CCC3=C(C2=O)C4=CC=CC=C4N3C,1
262,CCC(=O)N(C1=CC=CC=C1)C2(CCN(CC2)CCN3C(=O)N(N=N...,1
263,CC1=NN=C2N1C3=C(C=C(C=C3)Cl)C(=NC2)C4=CC=CC=C4,1
264,CN(C)C1=NC(=NC(=N1)N(C)C)N(C)C,0
265,C1C2CC3CC1CC(C2)(C3)N,1
266,CC(=O)OCC(=O)C12C(CC3C1(CC(C4(C3CCC5=CC(=O)C=C...,0
267,C[C@@]1([C@@H]2C[C@@H]3[C@H](C(=O)C(=C(N)[O-])...,1
268,CN(C)CC(C1=CC=C(C=C1)O)C2(CCCCC2)O,1
269,CC(=O)NC1=C(C(=C(C(=C1I)C(=O)O)I)NC(=O)C)I,1
270,C(CN)CNCCSP(=O)(O)O,1
271,C1C(C(C(C(C1NC(=O)C(CCN)O)OC2C(C(C(C(O2)CO)O)N...,0
272,CCC1(CCC(=O)NC1=O)C2=CC=C(C=C2)N,1
273,C1=CC(=CC=C1C(=O)NCC(=O)O)N,1
274,CN1C2=C(C(=O)N(C1=O)C)NC=N2,1
275,CCCCC1=C(C2=CC=CC=C2O1)C(=O)C3=CC(=C(C(=C3)I)O...,1
276,CCN1CCCC1CNC(=O)C2=CC(=C(C=C2OC)N)S(=O)(=O)CC,1
277,CN(C)CCC=C1C2=CC=CC=C2CCC3=CC=CC=C31,0
278,CC(C)C1=CC2=C(C=C1)OC3=NC(=C(C=C3C2=O)C(=O)O)N,0
279,CCOC(=O)C1=C(NC(=C(C1C2=CC=CC=C2Cl)C(=O)OC)C)C...,1
280,CCC1(C(=O)NC(=NC1=O)[O-])CCC(C)C,1
281,CCC(C)(C)C1=CC=C(C=C1)CC(C)CN2CC(OC(C2)C)C,1
282,C1CN(CCN1)C2=NC3=CC=CC=C3OC4=C2C=C(C=C4)Cl,0
283,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C...,1
284,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,1
285,CC(C)CN(CC(C(CC1=CC=CC=C1)NC(=O)OC2CCOC2)O)S(=...,0
286,COC1=C(C=CC(=C1)NS(=O)(=O)C)NC2=C3C=CC=CC3=NC4...,1
287,C1C2=C(C=CC(=C2Cl)Cl)NC3=NC(=O)CN31,0
288,CC(C)(C#N)C1=CC(=CC(=C1)CN2C=NC=N2)C(C)(C)C#N,1
289,CN1CCC2=CC=CC3=C2C1CC4=C3C(=C(C=C4)O)O,0
290,C1CN=C(N1)NC2=C(C=C(C=C2Cl)N)Cl,1
291,C[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CC(...,1
292,C(CC(=O)O)CO,1
293,CC1CCN(C(C1)C(=O)O)C(=O)C(CCCN=C(N)N)NS(=O)(=O...,1
294,C[C@H]([C@@H](C(=O)N[C@@H](CC1=CC=CC=C1)C(=O)N...,1
295,CC(=O)OC1=CC=CC=C1C(=O)O,1
296,CC(C)NCC(COC1=CC=C(C=C1)CC(=O)N)O,0
297,CC(C)C1=C(C(=C(N1CCC(CC(CC(=O)O)O)O)C2=CC=C(C=...,1
298,CN1C=NC(=C1SC2=NC=NC3=C2NC=N3)[N+](=O)[O-],1
299,C(CCCC(=O)O)CCCC(=O)O,1
300,CN1CCCC(CC1)N2C(=O)C3=CC=CC=C3C(=N2)CC4=CC=C(C...,1
301,CCC1C(C(C(N(CC(CC(C(C(C(C(C(=O)O1)C)OC2CC(C(C(...,1
302,CCCCC([C@]1(CC[C@H]2[C@H](O1)CC(=O)[C@@H]2CCCC...,1
303,COC(=O)CCC(=O)CN.Cl,1
304,CC1C(C(=O)N1S(=O)(=O)O)NC(=O)C(=NOC(C)(C)C(=O)...,1
305,C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@]2([C...,1
306,CCNC(=O)[C@@H]1CCCN1C(=O)[C@H](CCCN=C(N)N)NC(=...,1
307,CCNC(=O)[C@@H]1CCCN1C(=O)[C@H](CCCN=C(N)N)NC(=...,0
308,C1=CC(=CC=C1C(CC(=O)O)CN)Cl,0
309,CC[C@H](C)[C@@H](C(=O)N[C@@H](CO)C(=O)N[C@@H](...,0
310,CCC(=O)OCC(=O)C1(C(CC2C1(CC(C3(C2CCC4=CC(=O)C=...,1
311,CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)CO)O...,1
312,CCOC(=O)C(CCC1=CC=CC=C1)NC2CCC3=CC=CC=C3N(C2=O...,1
313,C1=CC=C(C=C1)CC2NC3=C(C=C(C(=C3)C(F)(F)F)S(=O)...,0
314,CCCCCOC1=CC=C(C=C1)C2=CC(=NO2)C3=CC=C(C=C3)C(=...,1
315,CCOC(=O)C1=CC=C(C=C1)N,1
316,CC(CC1=CC=CC=C1)N(C)CC2=CC=CC=C2,1
317,CN1C2CCC1CC(C2)OC(C3=CC=CC=C3)C4=CC=CC=C4,1
318,C1=CC=C(C=C1)COC(=O)C2=CC=CC=C2,0
319,COCCOCCOCCOCCOCCOCCOCCOCCOCCOCCOCCOCCOCCOCCOCC...,1
320,CC1(C(N2C(S1)C(C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C,1
321,C1CN(CCC1OC(C2=CC=C(C=C2)Cl)C3=CC=CC=N3)CCCC(=O)O,1
322,CC(C)COCC(CN(CC1=CC=CC=C1)C2=CC=CC=C2)N3CCCC3,0
323,CCOP(=O)(OCC)SCC[N+](C)(C)C.[I-],0
324,C1=CC=C(C=C1)[C@H](CNCCC2=CC=C(C=C2)NC(=O)CC3=...,0
325,CCCCCCOC(=O)CCC(=O)CN.Cl,1
326,CCC(C(=O)N)N1CCCC1=O,1
327,CNCCC1=CC=CC=N1,1
328,CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)COP(...,1
329,CC(C)NCC(COC1=CC=C(C=C1)CCOCC2CC2)O,1
330,CC(C[N+](C)(C)C)OC(=O)N,0
331,CCC(C1=CC(=CC=C1)O)C(C)CN(C)C,1
332,CC(CS(=O)(=O)C1=CC=C(C=C1)F)(C(=O)NC2=CC(=C(C=...,1
333,CC(C)OC(=O)CCC/C=C/CC1C(CC(C1/C=C/C(COC2=CC=CC...,0
334,CC[C@H](C)[C@@H](C(=O)N[C@@H](C(C)C)C(=O)N[C@@...,1
335,CC(=O)OC1=CC=C(C=C1)C(C2=CC=C(C=C2)OC(=O)C)C3=...,1
336,CC[C@H](C)[C@@H](C(=O)N[C@@H](CC(C)C)C(=O)NCC(...,1
337,CCC1=C(C=C2CC(CC2=C1)NCC(C3=C4C=CC(=O)NC4=C(C=...,1
338,CC[C@H](C)[C@@H](C(=O)N[C@@H](CC(C)C)C(=O)N1CC...,1
339,C1COCC(=O)N1C2=CC=C(C=C2)N3CC(OC3=O)CNC(=O)C4=...,1
340,CC(C)NCC(COC1=CC=C(C=C1)COCCOC(C)C)O,1
341,CC(C)NCC(COC1=CC=C(C=C1)CCC(=O)OC)O,0
342,C1C(C(C(C(N1CCO)CO)O)O)O,0
343,CC[N+](C)(C)CC1=CC=CC=C1Br,0
344,C1CN=C(N1)NC2=C(C3=NC=CN=C3C=C2)Br,1
345,C[C@H]1C[C@@H]2[C@H](CC[C@]3([C@H]2CC[C@@]3(C(...,1
346,C1C(=O)NC2=C(C=C(C=C2)Br)C(=N1)C3=CC=CC=N3,1
347,CN(CC1=CC(=CC(=C1N)Br)Br)C2CCCCC2,1
348,CC(C)CC1C(=O)N2CCCC2C3(N1C(=O)C(O3)(C(C)C)NC(=...,0
349,CC1([C@@H]2[C@H]1[C@H](N(C2)C(=O)[C@H](C(C)(C)...,1
350,C[C@H]([C@@H](C(=O)O)N)O[C@@H]1[C@@H]([C@H]([C...,1
351,CCCC1OC2CC3C4CCC5=CC(=O)C=CC5(C4C(CC3(C2(O1)C(...,1
352,CN1C2=C(C(=O)N(C1=O)C)NC(=N2)Cl.CN(C)CCOC(C1=C...,0
353,CCCCNC1=C(C(=CC(=C1)C(=O)O)S(=O)(=O)N)OC2=CC=C...,0
354,CCCCN1CCCCC1C(=O)NC2=C(C=CC=C2C)C,1
355,CC(C)(C)C(C)(C1CC23CCC1(C4C25CCN(C3CC6=C5C(=C(...,1
356,C1CCC2(C1)CC(=O)N(C(=O)C2)CCCCN3CCN(CC3)C4=NC=...,1
357,CS(=O)(=O)OCCCCOS(=O)(=O)C,1
358,CCC(C)C1(C(=O)NC(=O)NC1=O)CC,1
359,CCCCN1C[C@@H]([C@H]([C@@H]([C@H]1CO)O)O)O,0
360,CC(C)(C)C1=CC=C(C=C1)CN(C)CC2=CC=CC3=CC=CC=C32,0
361,CC(C)C(=O)OC1=C(C=C(C=C1)CO)[C@H](CCN(C(C)C)C(...,1
362,C1CCC2(C3CC4=C(C2(C1)CCN3CC5CCC5)C=C(C=C4)O)O,0
363,C1=CC(=CC=C1NC(=NC(=NCCCCCCN=C(N)N=C(N)NC2=CC=...,1
364,CCNC(=O)N(CCCN(C)C)C(=O)C1CC2C(CC3=CNC4=CC=CC2...,1
365,CC(C[N+](C)(C)C)OC(=O)C,1
366,CN1C=NC2=C1C(=O)N(C(=O)N2C)C,1
367,CC(C)C(CCCN(C)CCC1=CC(=C(C=C1)OC)OC)(C#N)C2=CC...,1
368,CC(C=CC(C1CC1)O)C2CCC3C2(CCCC3=CC=C4CC(CC(C4=C...,1
369,CC(CCCC(C)(C)O)C1CCC2C1(CCCC2=CC=C3CC(CC(C3=C)...,1
370,COC1=C(C=C2C(=C1)CC(C2=O)CC3CCN(CC3)CC4=CC=CC=...,1
371,CCOC1=NC2=CC=CC(=C2N1CC3=CC=C(C=C3)C4=CC=CC=C4...,1
372,CCOC1=NC2=CC=CC(=C2N1CC3=CC=C(C=C3)C4=CC=CC=C4...,0
373,C1CN=C(NC1C2C(=O)NCC(C(=O)NC(C(=O)NC(C(=O)NC(=...,1
374,CC(C)C=CCCCCC(=O)NCC1=CC(=C(C=C1)O)OC,0
375,CC(CS)C(=O)N1CCCC1C(=O)O,1
376,C[N+](C)(C)CCOC(=O)N,0
377,C1=CC=C2C(=C1)C=CC3=CC=CC=C3N2C(=O)N,1
378,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)C(=O)[...,1
379,CC(CC1=CC(=C(C=C1)O)O)(C(=O)O)NN,1
380,CN(C)CCOC(C1=CC=C(C=C1)Cl)C2=CC=CC=N2,0
381,CCCC(C)(COC(=O)N)COC(=O)NC(C)C,0
382,CC1=CN=C(C=[N+]1[O-])C(=O)O,1
383,C(CCl)NC(=O)N(CCCl)N=O,1
384,CC(C)(C)NCC(COC1=CC=CC2=C1CCC(=O)N2)O,1
385,COC1=CC=CC=C1OCCNCC(COC2=CC=CC3=C2C4=CC=CC=C4N3)O,1
386,C1C(=C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=...,1
387,CC1=C(N2C(C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)SC1)...,1
388,C1CC(N(C1)C(=O)C2CSSCC(C(=O)NC(C(=O)NC(C(=O)NC...,1
389,CC1=NN=C(S1)SCC2=C(N3C(C(C3=O)NC(=O)CN4C=NN=N4...,1
390,C[N+]1(CCCC1)CC2=C(N3C(C(C3=O)NC(=O)C(=NOC)C4=...,1
391,CC(=O)OCC1=C(N2C(C(C2=O)NC(=O)C(=NOC)C3=CSC(=N...,1
392,COC1(C2N(C1=O)C(=C(CS2)COC(=O)N)C(=O)[O-])NC(=...,1
393,C(CSC[C@@H]1[C@@H]2[C@@H]([C@H]([C@H](O1)O[C@@...,1
394,CC=CC1=C(N2C(C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)S...,1
395,CC(C)(C(=O)O)ON=C(C1=CSC(=N1)N)C(=O)NC2C3N(C2=...,1
396,C1C=C(N2C(S1)C(C2=O)NC(=O)C(=CCC(=O)O)C3=CSC(=...,1
397,CON=C(C1=CSC(=N1)N)C(=O)NC2C3N(C2=O)C(=CCS3)C(...,1
398,CN1C(=NC(=O)C(=N1)[O-])SCC2=C(N3C(C(C3=O)NC(=O...,1
399,CON=C(C1=CC=CO1)C(=O)NC2C3N(C2=O)C(=C(CS3)COC(...,1
400,CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(=O)(=O)...,1
401,CCN(CC)C(=O)NC1=CC(=C(C=C1)OCC(CNC(C)(C)C)O)C(...,0
402,CC1=C(N2C(C(C2=O)NC(=O)C(C3=CC=CC=C3)N)SC1)C(=O)O,1
403,CC1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3=C(OC4=CC(=CC(...,0
404,[CH2]CC=O,1
405,C=CC1=C(N2C(C(C2=O)NC(=O)C(=NOCC(=O)O)C3=CSC(=...,1
406,CC(C)C1=C(C(=C(C(=N1)C(C)C)C=CC(CC(CC(=O)O)O)O...,1
407,C1CN(CCN1CCOCC(=O)O)C(C2=CC=CC=C2)C3=CC=C(C=C3)Cl,1
408,CC(C)[C@H]1C(=O)N[C@H](C(=O)N([C@H](C(=O)N[C@H...,0
409,CC1OC2(CN3CCC2CC3)CS1,1
410,CC1=C[C@@H]2[C@H](CC[C@]3([C@H]2CC[C@@]3(C(=O)...,1
411,CC(C)(CC1=CC=C(C=C1)OC)NCC(C2=CC(=CC3=C2OCC(=O...,0
412,CCCCCOC1=CC=C(C=C1)C2=CC=C(C=C2)C3=CC=C(C=C3)C...,1
413,CN=C1CN(C(=C2C=C(C=CC2=N1)Cl)C3=CC=CC=C3)O,0
414,C1=CC(=CC=C1NC(=NC(=NCCCCCCN=C(N)N=C(N)NC2=CC=...,1
415,C1=CN=CC=C1N,1
416,CCN(CC)CCCC(C)NC1=C2C=CC(=CC2=NC=C1)Cl,1
417,C1=C2C(=CC(=C1Cl)S(=O)(=O)N)S(=O)(=O)N=CN2,1
418,CN(C)CCC(C1=CC=C(C=C1)Cl)C2=CC=CC=N2,0
419,CN(C)CCCN1C2=CC=CC=C2SC3=C1C=C(C=C3)Cl,1
420,CCCNC(=O)NS(=O)(=O)C1=CC=C(C=C1)Cl,0
421,C(O)(P(=O)(O)O)P(=O)(O)O,1
422,C1=CC=C2C(=C1)C(=O)NC2(C3=CC(=C(C=C3)Cl)S(=O)(...,1
423,C1=CC2=C(C=C1Cl)NC(=O)O2,1
424,[Se],0
425,CC1=CC(=O)N(C(=C1)C2CCCCC2)O,1
426,CCOC(=O)C(CCC1=CC=CC=C1)NC2CCCN3CCCC(N3C2=O)C(...,1
427,C1CCC(CC1)N2C(=NN=N2)CCCCOC3=CC4=C(C=C3)NC(=O)CC4,0
428,CC1=C(N=CN1)CSCCNC(=NC)NC#N,1
429,CCN1C2=CC3=C(C=C2C(=O)C(=N1)C(=O)O)OCO3,1
430,C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O,1
431,[NH2-].[NH2-].Cl[Pt+2]Cl,1
432,CN(C)CCCC1(C2=C(CO1)C=C(C=C2)C#N)C3=CC=C(C=C3)F,1
433,CCCC1=NC2=C(C=C(C=C2N1CC3=CC=C(C=C3)C4=CC=CC=C...,1
434,CC(C1=CC=CC=C1)(C2=CC=C(C=C2)Cl)OCCC3CCCN3C,1
435,CCCC1CC(N(C1)C)C(=O)NC(C2C(C(C(C(O2)SC)O)O)O)C...,1

In [12]:
# Creating molecular object from Smiles

PandasTools.AddMoleculeColumnToFrame(df,'smiles','mol')

[12:23:24] WARNING: not removing hydrogen atom without neighbors
[12:23:24] WARNING: not removing hydrogen atom without neighbors
[12:23:24] WARNING: not removing hydrogen atom without neighbors
[12:23:24] WARNING: not removing hydrogen atom without neighbors
[12:23:24] WARNING: not removing hydrogen atom without neighbors
[12:23:24] WARNING: not removing hydrogen atom without neighbors
[12:23:24] WARNING: not removing hydrogen atom without neighbors
[12:23:24] WARNING: not removing hydrogen atom without neighbors
[12:23:25] WARNING: not removing hydrogen atom without neighbors
[12:23:25] WARNING: not removing hydrogen atom without neighbors
[12:23:25] WARNING: not removing hydrogen atom without neighbors
[12:23:25] WARNING: not removing hydrogen atom without neighbors
[12:23:25] WARNING: not removing hydrogen atom without neighbors

In [13]:
df = df.dropna(subset=['mol'])

In [14]:
df

,smiles,Immune system disorders,mol
0,C(CNCCNCCNCCN)N,0,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7d80>
1,CC(C)(C)C1=CC(=C(C=C1NC(=O)C2=CNC3=CC=CC=C3C2=...,0,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7060>
2,CC[C@]12CC(=C)[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7920>
3,CCC12CC(=C)C3C(C1CC[C@]2(C#C)O)CCC4=CC(=O)CCC34,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e6f10>
4,C1C(C2=CC=CC=C2N(C3=CC=CC=C31)C(=O)N)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7a70>
5,CC[C@H](C)[C@H]1C(=O)N[C@H]2CSSC[C@@H](C(=O)N[...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7140>
6,CC1CC2C3CCC4=CC(=O)C=CC4([C@]3(C(CC2([C@]1(C(=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7220>
7,CCCCCCOC(=O)N=C(C1=CC=C(C=C1)NCC2=NC3=C(N2C)C=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e73e0>
8,CSCCC(C(=O)NCC(=O)NC(CC1=CNC2=CC=CC=C21)C(=O)N...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7990>
9,C1CC(N(C1)C(=O)C2CSSCC(C(=O)NC(C(=O)NC(C(=O)NC...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e70d0>
10,CC(C)CN(C[C@H]([C@H](CC1=CC=CC=C1)NC(=O)O[C@H]...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e6ff0>
11,C1CC[C@H]([C@@H](C1)CN2CCN(CC2)C3=NSC4=CC=CC=C...,0,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7f40>
12,CCCSC1=NC2=C(C(=N1)N[C@@H]3C[C@H]3C4=CC(=C(C=C...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7840>
13,C1CN(CC2=C1SC=C2)CC3=CC=CC=C3Cl,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7ae0>
14,Cl[Tl],1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7300>
15,CC1=NN=C(N1C2CC3CCC(C2)N3CC[C@@H](C4=CC=CC=C4)...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7e60>
16,C[N+](C)(C)CC(CC(=O)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7ca0>
17,CN1C2=C(C=C(C=C2)N(CCCl)CCCl)N=C1CCCC(=O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7bc0>
18,CCN(CC)C(=O)/C(=C/C1=CC(=C(C(=C1)O)O)[N+](=O)[...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7a00>
19,C(CC(=O)O)CN,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7760>
20,C[C@H]1C[C@H]2[C@@H]3C[C@@H](C4=CC(=O)C=C[C@@]...,0,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7450>
21,CC(C)CN1C=NC2=C1C3=CC=CC=C3N=C2N,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7680>
22,CC[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e76f0>
23,CC1=CC(=C(N1)C=C2C3=CC=CC=C3NC2=O)C,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7370>
24,C(CC(=O)O)C(=O)CN,0,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7610>
25,C1C(N(C2=C(N1)NC(=NC2=O)N)C=O)CNC3=CC=C(C=C3)C...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7290>
26,CCC12CC(=C)C3C(C1CC[C@]2(C#C)O)CCC4=CC(=O)CCC3...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e78b0>
27,CN1C(CNC2=C1C(=O)N=C(N2)N)CNC3=CC=C(C=C3)C(=O)...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7d10>
28,CCCCC(=O)O[C@@]1([C@H](C[C@@H]2[C@@]1(C[C@@H](...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e77d0>
29,CC[C@H](C)[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7b50>
30,CCCCCC(C=CC1C(CC(=O)C1CC=CCCCC(=O)O)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e74c0>
31,CCCCCC(C=CC1C(CC2C1CC(=CCCCC(=O)O)O2)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e71b0>
32,CCCCCC(C=CC1C(CC(C1CC=CCCCC(=O)O)O)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e75a0>
33,CC(=O)O.C(C(C(C(C(C=O)O)O)O)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904040>
34,CC(=O)[O-],0,<rdkit.Chem.rdchem.Mol object at 0x7c67689040b0>
35,CC(=O)OCC[N+](C)(C)C,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904120>
36,C1=NC2=C(C(=N1)N)N=CN2C3C(C(C(O3)CO)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904190>
37,CCCN(CCC1=CC=CS1)C2CCC3=C(C2)C=CC=C3O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904200>
38,C1=CO[C@@H]([C@H]([C@@H]1O)O)C(=O)O.Cl,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904270>
39,C(C1C(C(C(C(O1)O)O)O)O)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689042e0>
40,CCCCCC(C=CC1C(CC(=O)C1CCCCCCC(=O)O)O)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904350>
41,N,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689043c0>
42,CC1=CC2=C(C=C1C(=C)C3=CC=C(C=C3)C(=O)O)C(CCC2(...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904430>
43,CC(=O)NCCC1=CC=CC2=C1C=C(C=C2)OC,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689044a0>
44,C(CC(C(=O)O)N)CN=C(N)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904510>
45,C1=CC=C(C=C1)CO,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904580>
46,C[N+](C)(C)CC(=O)[O-],0,<rdkit.Chem.rdchem.Mol object at 0x7c67689045f0>
47,CC[C@H](C)[C@@H](C(=O)N[C@@H](CC1=CC=C(C=C1)O)...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904660>
48,CCCC1=NC(=C2N1NC(=NC2=O)C3=C(C=CC(=C3)S(=O)(=O...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689046d0>
49,CN1CC(=O)N2[C@@H](C1=O)CC3=C([C@H]2C4=CC5=C(C=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904740>
50,I,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689047b0>
51,[Ca+2],1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904820>
52,C[C@]12CCC(=O)C=C1[C@@H]3C[C@@H]3[C@@H]4[C@@H]...,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904890>
53,C,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904900>
54,C1=CC(=CC=C1C(C(CO)NC(=O)C(Cl)Cl)O)[N+](=O)[O-],1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904970>
55,CC(CCC(=O)O)C1CCC2C1(C(CC3C2C(CC4C3(CCC(C4)O)C...,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689049e0>
56,CC1=NC=CN1.C1C(O1)CCl,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904a50>
57,C[N+](C)(C)CCO,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904ac0>
58,C(C(=O)O)C(CC(=O)O)(C(=O)O)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904b30>
59,[Cl-],0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904ba0>
60,COC1=CC=C(C=C1)N2C3=C(CCN(C3=O)C4=CC=C(C=C4)N5...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904c10>
61,CCOC1=CC=CC=C1O[C@H]([C@@H]2CNCCO2)C3=CC=CC=C3,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904c80>
62,C1=CC2=C(C(=C1)Cl)SC=C2COC(CN3C=CN=C3)C4=C(C=C...,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904cf0>
63,CC1=C(C(C(=C(N1)C)C(=O)OC(C)(C)CN(C)CCC(C2=CC=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904d60>
64,C1=CC=C(C(=C1)C(=O)O)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904dd0>
65,CC1=CC=CN2C1=NC=C(C2=O)C3=NNN=N3,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904e40>
66,CC1=CC(=C(C(=C1C=CC(=CC=CC(=CC(=O)O)C)C)C)C)OC,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904eb0>
67,C1C(C(=O)NO1)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768904f20>
68,CCN(CC)CCOC(=O)C1=C(C=C(C=C1)N)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768904f90>
69,CCOC1=CC=CC=C1OCCN[C@@H](C)CC2=CC(=C(C=C2)OC)S...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905000>
70,CC(C(=O)C1=CC(=CC=C1)Cl)NC(C)(C)C,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905070>
71,CC12CCC3C(C1CCC2O)CCC4=C3C=CC(=C4)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689050e0>
72,C(C(C(C(C(CO)O)O)O)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905150>
73,CC[C@@H]([C@H](C)O)N1C(=O)N(C=N1)C2=CC=C(C=C2)...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689051c0>
74,CC(C)CN(C[C@H]([C@H](CC1=CC=CC=C1)NC(=O)O[C@H]...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905230>
75,C1=CC=C2C(=C1)C(=O)OC23C4=C(C=C(C=C4)O)OC5=C3C...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689052a0>
76,CCC1=NC=CC(=C1)C(=S)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905310>
77,C1C(C(OC1N2C=NC(=NC2=O)N)CO)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905380>
78,C1=CC=C(C=C1)C2=NC3=C(N=C2N)N=C(N=C3N)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689053f0>
79,CC1=C(C(=O)N2CCCC(C2=N1)O)CCN3CCC(CC3)C4=NOC5=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905460>
80,C(CCC(=O)O)CCN,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689054d0>
81,CC(=O)NC(CS)C(=O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905540>
82,CN1CCC23C4C1CC5=C2C(=C(C=C5)OC)OC3C(C=C4)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689055b0>
83,C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905620>
84,C(CS(=O)(=O)O)S,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905690>
85,CNC1=CC=C(C=C1)/C=C/C2=CN=C(C=C2)OCCOCCOCC[18F],0,<rdkit.Chem.rdchem.Mol object at 0x7c6768905700>
86,CC(C(=O)O)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768905770>
87,CN1C2=C(C(=O)N(C1=O)C)NC=N2.C[N+](C)(C)CCO,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689057e0>
88,C#CCC(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C...,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768905850>
89,C1CC(=O)C(C(=O)C1)C(=O)C2=C(C=C(C=C2)C(F)(F)F)...,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689058c0>
90,C1=CC=C(C=C1)C(=C(C2=CC=CC=C2)C3=CC=C(C=C3)OCC...,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768905930>
91,[H+].[H+].CNC[C@@H]([C@H]([C@@H]([C@@H](CO)O)O...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67913c7d80>
92,CN1C[C@@H]2C(C1)C3=CC=CC=C3OC4=C2C=C(C=C4)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689059a0>
93,CS(=O)C,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768905a80>
94,C1=CC(=C(C=C1CCN)O)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768905af0>
95,CC12CCC3C(C1CCC2=O)CCC4=C3C=CC(=C4)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905b60>
96,CC12CCC3C(C1CCC2=O)CCC4=C3C=CC(=C4)OS(=O)(=O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905bd0>
97,C(CO)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905c40>
98,C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905cb0>
99,CC(C)OC(=O)CCCC=CC[C@H]1[C@H](C[C@H]([C@@H]1C=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905d20>
100,CC(=O)OC1=CC=CC=C1C(=O)NC2=NC=C(S2)[N+](=O)[O-],1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905d90>
101,CN(C)CCC1=CNC2=C1C=C(C=C2)CS(=O)(=O)N3CCCC3,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905e00>
102,C1(C(C(C(C(C1Cl)Cl)Cl)Cl)Cl)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768905e70>
103,C1CC2C(=O)NC(CSSCCC(=O)NC(C(=O)NCC(=O)NC(C(=O)...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905ee0>
104,CO[C@@H]1[C@@H]([C@H]([C@@H]([C@H](O1)COS(=O)(...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905f50>
105,CCC(=O)N(C1=CC=CC=C1)C2(CCN(CC2)CCC3=CC=CS3)COC,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768905fc0>
106,CC1CCC2CC(C(=CC=CC=CC(CC(C(=O)C(C(C(=CC(C(=O)C...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906030>
107,CC(C)(C)[C@@H](C(=O)N[C@@H](CC1=CC=CC=C1)[C@H]...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689060a0>
108,C(CC(=O)N)C(C(=O)O)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906110>
109,CC1=NC=C(C=C1)C2=NC=C(C=C2C3=CC=C(C=C3)S(=O)(=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906180>
110,C[C@@H]1C[C@H]2C3CCC4=CC(=O)C=C[C@@]4([C@]3([C...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689061f0>
111,C[C@]12CCC(=O)C=C1C[C@H](C3[C@]24C(O4)C[C@]5([...,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768906260>
112,CC1=C2C(=C(N(C1=O)C)NC3=C(C=C(C=C3)I)F)C(=O)N(...,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689062d0>
113,CCC(C)CC(C)CCCCCCCCC(=O)N[C@H]1C[C@@H]([C@H](N...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906340>
114,C(C(=O)O)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689063b0>
115,COC1=C(C=C2C(=C1)N=CN=C2NC3=CC(=C(C=C3)F)Cl)OC...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906420>
116,C(C(CO)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906490>
117,CC(=O)O[C@]1(CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906500>
118,C1C[C@H]2CN(C(=O)C3=C2C(=CC=C3)C1)[C@@H]4CN5CC...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906570>
119,C(=O)(O)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689065e0>
120,C[C@H](C1=CC=CC2=CC=CC=C21)NCCCC3=CC(=CC=C3)C(...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906650>
121,CC(=O)NC1C(C(C(OC1O)COS(=O)(=O)O)OC2C(C(C(C(O2...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689066c0>
122,C1=C(NC=N1)CCN,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906730>
123,CCCCC(=O)OCC(=O)[C@]1(C[C@@H](C2=C(C3=C(C(=C2C...,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689067a0>
124,C1=CC(=CC=C1O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906810>
125,CCOC1=C(C2=CC=CC=C2C=C1)C(=O)N[C@H]3[C@@H]4N(C...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906880>
126,[K+],0,<rdkit.Chem.rdchem.Mol object at 0x7c67689068f0>
127,C[C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@@H]2[C...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906960>
128,C1C(C(C(C(C1N)OC2C(C(C(C(O2)CN)O)O)O)O)OC3C(C(...,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689069d0>
129,CC1=CC(=CC=C1)NC2=C(C=NC=C2)S(=O)(=O)NC(=O)NC(C)C,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768906a40>
130,C1CC(N(C1)C(=O)CNC23CC4CC(C2)CC(C4)(C3)O)C#N,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768906ab0>
131,CNCC(C1=CC(=C(C=C1)O)O)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768906b20>
132,CCC#CC(C)C1(C(=O)NC(=O)N(C1=O)C)CC=C,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906b90>
133,C(P(=O)(O)O)(P(=O)(O)O)(Cl)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906c00>
134,C1=C(C=C(C(=C1I)OC2=CC(=C(C(=C2)I)O)I)I)CC(C(=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906c70>
135,C1=CC(=C(C=C1OC2=C(C=C(C=C2I)CC(C(=O)O)N)I)I)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768906ce0>
136,[Mg+2],0,<rdkit.Chem.rdchem.Mol object at 0x7c6768906d50>
137,CC(=O)NCCC1=CNC2=C1C=C(C=C2)OC,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906dc0>
138,CCNC(=NCCCC[C@H](C(=O)N[C@@H](CC(C)C)C(=O)N[C@...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906e30>
139,[Na+],1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906ea0>
140,C1=CC(=C(C=C1C[C@@H](C(=O)O)N)O)O.C1=CC(=C(C(=...,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768906f10>
141,C1=CC(=CN=C1)C(=O)[O-],1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906f80>
142,CCO.C[C@@H]1C2C(C3[C@@H](C(=O)C(=C([C@]3(C(=O)...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768906ff0>
143,CN1CCCC1C2=CN=CC=C2,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907060>
144,N(=O)[O-],0,<rdkit.Chem.rdchem.Mol object at 0x7c67689070d0>
145,N#[N+][O-],0,<rdkit.Chem.rdchem.Mol object at 0x7c6768907140>
146,CC(=O)[O-].[Na+],0,<rdkit.Chem.rdchem.Mol object at 0x7c67689071b0>
147,C1=CC(=C(C=C1C(CN)O)O)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768907220>
148,[OH-],0,<rdkit.Chem.rdchem.Mol object at 0x7c6768907290>
149,FS(F)(F)(F)(F)F,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907300>
150,OP(=O)(O)[O-],1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907370>
151,CN[C@@H]1CCC2=C(C1)C3=C(N2)C=CC(=C3)C(=O)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689073e0>
152,C[C@H](C(=O)N1CCC[C@H]1C(=O)O)N[C@@H](CCC2=CC=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907450>
153,CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CCCC(=O)OCC.CC/...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689074c0>
154,C1CN(CCN1CCCCC2=CNC3=C2C=C(C=C3)C#N)C4=CC5=C(C...,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768907530>
155,C=CC1=C(N2[C@@H]([C@@H](C2=O)NC(=O)C(=NO)C3=CS...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689075a0>
156,C[C@H](C=C[C@H](C)C(C)(C)O)[C@H]1CC[C@@H]2[C@@...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907610>
157,C1=CN=C(C=N1)C(=O)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907680>
158,CC1=NC=C(C(=C1O)CO)CO,0,<rdkit.Chem.rdchem.Mol object at 0x7c67689076f0>
159,COC1=CC2=C(C=CN=C2C=C1)C(C3CC4CCN3CC4C=C)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907760>
160,CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689077d0>
161,CCC(=O)OC1([C@@H](C[C@@H]2[C@@]1(C[C@@H](C3([C...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907840>
162,CC[C@H](C)[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67689078b0>
163,C[C@@H]1C[C@H]2[C@@H]3C[C@@H](C4=CC(=O)C=C[C@@...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907920>
164,CC1=CC(=NC(=N1)OC(C(=O)O)C(C2=CC=CC=C2)(C3=CC=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907990>
165,C(C[Ge](=O)O[Ge](=O)CCC(=O)O)C(=O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907a00>
166,C1C[N+]2(CCC1(CC2)C(C3=CC=CC=C3)(C4=CC=CC=C4)O...,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768907a70>
167,CC(C(C1CNC2=C(N1)C(=O)N=C(N2)N)O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907ae0>
168,C(COC[C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)OCCO)O...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907b50>
169,CC1=C(SC=[N+]1CC2=CN=C(N=C2N)C)CCO,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907bc0>
170,CC1=CN(C(=O)NC1=O)C2CC(C(O2)CO)O,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768907c30>
171,CCCC1=C2C(=CC3=C1OC(=CC3=O)C(=O)O)C(=O)C=C(N2C...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907ca0>
172,C(C(F)(F)F)(OC(F)F)F,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768907d10>
173,C(C(C(=O)O)S)(C(=O)O)S,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907d80>
174,C[C@H](C(=O)N)NC(=O)[C@@H]1CCCN1C(=O)[C@H](CCC...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907df0>
175,CN1CCC(CC1)COC2=C(C=C3C(=C2)N=CN=C3NC4=C(C=C(C...,0,<rdkit.Chem.rdchem.Mol object at 0x7c6768907e60>
176,CCCCCCCCCCNCCN[C@]1(C[C@@H](O[C@H]([C@H]1O)C)O...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907ed0>
177,CC(=O)[C@]1(CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2C=C(...,1,<rdkit.Chem.rdchem.Mol object at 0x7c6768907f40>
178,CC(CC1=CC=CC=C1)NC,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c190>
179,C1CC2=C(C=CC(=C2)Cl)C(=C3CCNCC3)C4=C1C=CC=N4,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c040>
180,CN1C2=C(C(=O)N(C1=O)C)NC=N2.CN1C2=C(C(=O)N(C1=...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c0b0>
181,C1CC(CCC1C2=CC=C(C=C2)Cl)C3=C(C4=CC=CC=C4C(=O)...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c120>
182,C[C@H]([C@@H](C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H]...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c200>
183,C[C@@H](CC1=CC2=C(C(=C1)C(=O)N)N(CC2)CCCO)NCCO...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c270>
184,CCC1/C=C(/C(C/C=C/C=C(\C(=O)OC(C/C=C(/C=C(/C1O...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c2e0>
185,CC(C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)[O-].[Na+],1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c350>
186,COC1=C(C=C(C=C1)CCO[C@@H]2CCCC[C@H]2N3CC[C@H](...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885c3c0>
187,C1[C@H](SC(=C(C#N)N2C=CN=C2)S1)C3=C(C=C(C=C3)C...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885c430>
188,CCCCC1=NC2(CCCC2)C(=O)N1CC3=CC=C(C=C3)C4=CC=CC...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c4a0>
189,CC[C@H](C)[C@@H](C(=O)N[C@@H]([C@@H](C)O)C(=O)...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885c510>
190,C[C@]12C[C@@H]([C@]3([C@H]([C@@H]1C[C@H]([C@@]...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885c580>
191,[C-]#N.[C-]#N.[C-]#N.[C-]#N.[C-]#N.[C-]#N.[Fe+2],0,<rdkit.Chem.rdchem.Mol object at 0x7c676885c5f0>
192,CC1=C(C=CC2=C1N=C(C=C2OC3C[C@@H]4[C@@H](C3)C(=...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885c660>
193,CCCCC(=O)O[C@@]1(CCC2C1(CC(C3C2CCC4=CC(=O)CCC3...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885c6d0>
194,CN1C(=NN=N1)SCC2=C(N3C([C@@](C3=O)(NC(=O)C4SC(...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c740>
195,CC[PH+](CC)CC.CC[PH+](CC)CC.CC(=O)OCC1C(C(C(C(...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885c7b0>
196,CCCCCCCCC1=CC=C(C=C1)CCC(CO)(CO)N.Cl,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c820>
197,CC[C@H](C)[C@H]1C(=O)N[C@H](C(=O)N[C@H](C(=O)N...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c890>
198,CC(C)[C@@H](CO)N1C=C(C(=O)C2=CC(=C(C=C21)OC)CC...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c900>
199,C[C@H]1C=CC=C(C(=O)NC2=C3C(=NC4(N3)CCN(CC4)CC(...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c970>
200,C[C@@H](C(=O)N1CC2=CC=CC=C2C[C@H]1C(=O)O)N[C@@...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885c9e0>
201,CC[C@H](C)[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885ca50>
202,CC(=O)C1(CCC2C1(CC(C3=C4CCC(=O)C=C4CCC23)C5=CC...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885cac0>
203,CN(C)CC[C@@](C1=CC=CC2=CC=CC=C21)([C@@H](C3=CC...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885cb30>
204,C1CCC(CC1)[C@@H]2C[C@H](NC2)C(=O)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885cba0>
205,C1C2=CC=CC=C2N(C3=CC=CC=C3C1=O)C(=O)N,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885cc10>
206,C1C(C(OC1N2C=NC3=C2N=C(N=C3N)Cl)CO)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885cc80>
207,[H-].[H-].[Ba+2],0,<rdkit.Chem.rdchem.Mol object at 0x7c676885ccf0>
208,C[C@]12CCC(=O)C=C1CC[C@@H]3[C@@H]2C(=O)C[C@]4(...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885cdd0>
209,CCOC(=O)N[C@@H]1CC[C@@H]2[C@@H](C1)C[C@@H]3[C@...,0,<rdkit.Chem.rdchem.Mol object at 0x7c676885cd60>
210,CC1=C(SC=N1)C=CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885ce40>
211,COCCNC(=O)CN(CCN(CCN(CC(=O)NCCOC)CC(=O)[O-])CC...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885ceb0>
212,CCNC(=O)C1CCCN1C(=O)C(CCCN=C(N)N)NC(=O)C(CC(C)...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885cf20>
213,CC(C)C(=O)OCC(=O)[C@@]12[C@@H](C[C@@H]3[C@@]1(...,1,<rdkit.Chem.rdchem.Mol object at 0x7c676885cf90>

**Morgan Fingerprint**

In [15]:
df_mf = []
for mol in df['mol']:
  mf_bitvector = AllChem.GetMorganFingerprintAsBitVect(mol, radius=1, nBits = 2048)
  arr = np.zeros((0,), dtype=np.int8)
  # convert the RDKit explicit vectors into numpy arrays
  DataStructs.ConvertToNumpyArray(mf_bitvector,arr)
  df_mf.append(arr)

MF = pd.concat([df, pd.DataFrame(df_mf)], axis=1)

[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator
[12:23:48] DEPRECATION WARNING: please use MorganGenerator

In [16]:
MF.head()

,smiles,Immune system disorders,mol,0,1,2,3,4,5,6,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
0,C(CNCCNCCNCCN)N,0,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7d80>,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CC(C)(C)C1=CC(=C(C=C1NC(=O)C2=CNC3=CC=CC=C3C2=...,0,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7060>,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CC[C@]12CC(=C)[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O...,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7920>,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CCC12CC(=C)C3C(C1CC[C@]2(C#C)O)CCC4=CC(=O)CCC34,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e6f10>,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,C1C(C2=CC=CC=C2N(C3=CC=CC=C31)C(=O)N)O,1,<rdkit.Chem.rdchem.Mol object at 0x7c67687e7a70>,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
# print first molecule in the dataset
display(MF.iloc[0,1])
nmpyrrole = MF.iloc[0,2:]

# get the number of ones and zeros in the first molecule
print(f'No of ones in the N-Methyl pyrrole MF are:  {nmpyrrole[nmpyrrole==1].count()}')
print(f'No of zeros in the N-Methyl pyrrole MF are:  {nmpyrrole[nmpyrrole==0].count()} \n')

# grab the column names where bits are 1s
print(nmpyrrole[nmpyrrole==1])

# print second molecule in the dataset
display(MF.iloc[1,1])
pyrrole = MF.iloc[1,2:]

# get the number of ones and zeros in the second molecule
print(f'No of ones in the pyrrole MF are:  {nmpyrrole[pyrrole==1].count()}')
print(f'No of zeros in the pyrrole MF are:  {nmpyrrole[pyrrole==0].count()} \n')

# get the column names where bits are 1s
print(pyrrole[pyrrole==1])

np.int64(0)

No of ones in the N-Methyl pyrrole MF are:  7
No of zeros in the N-Methyl pyrrole MF are:  2041

80      1
667     1
981     1
1004    1
1152    1
1171    1
1840    1
Name: 0, dtype: object

np.int64(0)

No of ones in the pyrrole MF are:  27
No of zeros in the pyrrole MF are:  2021

114     1
119     1
314     1
392     1
419     1
486     1
525     1
650     1
806     1
807     1
875     1
1057    1
1088    1
1114    1
1152    1
1224    1
1339    1
1357    1
1380    1
1602    1
1607    1
1750    1
1816    1
1873    1
1879    1
1917    1
1991    1
Name: 1, dtype: object

**Extended Connectivity Circular Fingerprint (ECFP)**

In [18]:
df_ecfp = []
for mol in df['mol']:
    # radius=2 is the standard for ECFP4
    ecfp_bitvector = AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048)
    arr = np.zeros((0,), dtype=np.int8)
    DataStructs.ConvertToNumpyArray(ecfp_bitvector, arr)
    df_ecfp.append(arr)

[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator
[12:24:13] DEPRECATION WARNING: please use MorganGenerator

In [19]:
# Ensure 'Immune system disorders' is the exact column name from your sider.xlsx
ECFP_Final = pd.concat([df[['Immune system disorders']], pd.DataFrame(df_ecfp)], axis=1)

In [20]:
print(ECFP_Final.head())

   Immune system disorders  0  1  2  3  4  5  6  7  8  ...  2038  2039  2040  \
0                        0  0  0  0  0  0  0  0  0  0  ...     0     0     0
1                        0  0  0  0  0  0  0  0  0  0  ...     0     0     0
2                        1  0  0  0  0  0  0  0  0  0  ...     0     0     0
3                        1  0  0  0  0  0  0  0  0  0  ...     0     0     0
4                        1  1  0  0  0  0  0  0  0  0  ...     0     0     0

   2041  2042  2043  2044  2045  2046  2047
0     0     0     0     0     0     0     0
1     0     0     0     0     0     0     0
2     0     0     0     0     0     0     0
3     0     0     0     0     0     0     0
4     0     0     1     0     0     0     0

[5 rows x 2049 columns]